# Generated by Django 5.2.3 on 2025-07-14 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Введите корректный email адрес')], verbose_name='Почта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('data_agreement', models.BooleanField(default=False, verbose_name='Подтверждаю использование данных')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
